### ISSUE TITLE
large se of heritability

### ISSUE THREAD

**Issue by Xuemin-Wang** [zhenin/HDL#10]
Dear Zheng,

Does HDL require heritability of both traits to be significant so the genetic correlation can be stable enough to be meaningful? One of the traits included in the rg analysis has a low h2 (0.009) but high se (0.0248). Its sample size is 36,677,  which is not ridiculously small. I guess it will be impossible to find a trait that is significantly genetically correlated with this trait because of its non-significant rg using gwas summary statistics. Can you think of a method to reduce se of h2 to improve rg estimation?

Please find the full log below:
res.HDL <- HDL.rg(trait_1, trait_2, LD.path)
Analysis starts on Wed Nov 25 09:29:42 2020
1024186 out of 1029876 (99.45%) SNPs in reference panel are available in GWAS 1.
1025613 out of 1029876 (99.59%) SNPs in reference panel are available in GWAS 2.
Estimation is ongoing ... 100%

Integrating piecewise results

Point estimates:
Heritability of phenotype 1:  0.009
Heritability of phenotype 2:  0.0606
Genetic Covariance:  0.0107
Genetic Correlation:  0.4564

Continuing computing standard error with jackknife
Progress... 100%

Heritability of phenotype 1:  0.009 (0.0248)
Heritability of phenotype 2:  0.0606 (0.0082)
Genetic Covariance:  0.0107 (0.0062)
Genetic Correlation:  0.4564 (6.4041)
P:  9.43e-01

I also used the munged sumstats by LDSC (1,025,613 SNPs) and the full sumstats only with the required columns (9,523,650 SNPs) of trait 2 for rg estimation. There were huge difference between the h2 of trait 2 using the two sumstats (0.0606 vs. 0.3495)! Do you know what might cause the difference. Below is the log of including the full sumstats:
res.HDL_new <- HDL.rg(trait_1, trait_2, LD.path)
Analysis starts on Wed Nov 25 11:50:31 2020
1024186 out of 1029876 (99.45%) SNPs in reference panel are available in GWAS 1.
1025614 out of 1029876 (99.59%) SNPs in reference panel are available in GWAS 2.
Estimation is ongoing ... 100%

Integrating piecewise results

Point estimates:
Heritability of phenotype 1:  0.009
Heritability of phenotype 2:  0.3495
Genetic Covariance:  0.0262
Genetic Correlation:  0.4669

Continuing computing standard error with jackknife
Progress... 100%

Heritability of phenotype 1:  0.009 (0.0248)
Heritability of phenotype 2:  0.3495 (0.0676)
Genetic Covariance:  0.0262 (0.0199)
Genetic Correlation:  0.4669 (6.5598)
P:  9.43e-01

Many thanks,
xuemin

**Comment by zhenin** [comment]
Dear Xuemin,

Thanks for using HDL! Although low h2 with large se would generally lead to insignificant rg, it is not necessarily always like that. But in your case, I would say you are right that h2 = 0.009 (0.0248) is too small to generate any significant rg. Unfortunately, we do not have any magic to save this for now.

The huge difference is weird as the HDL reference panel is a subset of LDSC panel. Could you update HDL to the latest version (v1.3.9)? If the difference is still there, it will be very interesting to check the reason!

Best,
Zheng
