### ISSUE TITLE
Why can't I use the panel UKB_imputed_hapmap2_SVD_eigen99_extraction

### ISSUE THREAD

**Issue by fry3682665** [zhenin/HDL#12]
i am sure that this reference panel is in the reference folder
![image](https://user-images.githubusercontent.com/75370141/102205252-eab44080-3f05-11eb-9e34-b626e2888343.png)

**Comment by zhenin** [comment]
Thanks for reporting this! I will change the error report so that it becomes more specific. 

Could you list the files in the reference folder with `ls` command?

**Comment by fry3682665** [comment]
> Thanks for reporting this! I will change the error report so that it becomes more specific.

![image](https://user-images.githubusercontent.com/75370141/102335468-edc53480-3fca-11eb-8873-2dc02f9c5fe7.png)
I am very happy to receive your reply

**Comment by zhenin** [comment]
Thanks! Could you list the files in folder 'UKB_imputed_hapmap2_SVD_eigen99_extraction'?

**Comment by fry3682665** [comment]
![image](https://user-images.githubusercontent.com/75370141/102336306-f79b6780-3fcb-11eb-9a97-49b1365ff19f.png)
Thank you very much for your reply

**Comment by zhenin** [comment]
Thanks a lot! Now I know the bug: I did not put some important files required in the latest HDL version in this gz file. I will fix it soon. I will update you when this was done.

**Comment by fry3682665** [comment]
Thanks a lot! But I don't know if the problem with the reference panel is the reason why I failed to do HDL arithmetic
