### ISSUE TITLE
error

### ISSUE THREAD

**Issue by fry3682665** [zhenin/HDL#13]
![image](https://user-images.githubusercontent.com/75370141/102215032-16d6be00-3f14-11eb-8afb-a3c223fe35df.png)

**Comment by zhenin** [comment]
This is indeed weird! Are you just testing the example files? I will look into it.

**Comment by fry3682665** [comment]
It is not a test file, but my own GWAS Summary file, because in my previous use it seems that the HDL operation can only be performed if I change my file name to the same file name as the test file and remove the test file.

**Comment by fry3682665** [comment]
![image](https://user-images.githubusercontent.com/75370141/102336576-4fd26980-3fcc-11eb-914d-8d8ae43bce2a.png)
This is my data. Is there a problem with the data?Another request is that I am also having trouble with this data when doing LDSC analysis. The problem has been commented on the GIthub of LDSC and I really hope to get your advice

**Comment by zhenin** [comment]
> It is not a test file, but my own GWAS Summary file, because in my previous use it seems that the HDL operation can only be performed if I change my file name to the same file name as the test file and remove the test file.

HDL should be smarter :) You should be able to specify your own file name by setting `gwas1.df=` and `gwas1.df=`.



> ![image](https://user-images.githubusercontent.com/75370141/102336576-4fd26980-3fcc-11eb-914d-8d8ae43bce2a.png)
> This is my data. Is there a problem with the data?Another request is that I am also having trouble with this data when doing LDSC analysis. The problem has been commented on the GIthub of LDSC and I really hope to get your advice

The only thing I find a bit abnormal according to the screenshot is that most of SNPs are without rsid. How many SNPs you have in the GWAS files? Could you try to run with UKB_imputed_SVD_eigen99_extraction reference panel? This is the most standard panel we recommend our users to use. This panel is a subset of LDSC 1000 Genomes panel. If too many SNPs in this panel miss in your GWAS, then there might be some issue for both HDL and LDSC.

**Comment by fry3682665** [comment]
Thank you very much. It seems that the lack of SNPID is my main mistake. I still want to ask you how to add SNPID in GWAS Summary

**Comment by fry3682665** [comment]
> > It is not a test file, but my own GWAS Summary file, because in my previous use it seems that the HDL operation can only be performed if I change my file name to the same file name as the test file and remove the test file.
> 
> HDL should be smarter :) You should be able to specify your own file name by setting `gwas1.df=` and `gwas1.df=`.
> 
> > ![image](https://user-images.githubusercontent.com/75370141/102336576-4fd26980-3fcc-11eb-914d-8d8ae43bce2a.png)
> > This is my data. Is there a problem with the data?Another request is that I am also having trouble with this data when doing LDSC analysis. The problem has been commented on the GIthub of LDSC and I really hope to get your advice
> 
> The only thing I find a bit abnormal according to the screenshot is that most of SNPs are without rsid. How many SNPs you have in the GWAS files? Could you try to run with UKB_imputed_SVD_eigen99_extraction reference panel? This is the most standard panel we recommend our users to use. This panel is a subset of LDSC 1000 Genomes panel. If too many SNPs in this panel miss in your GWAS, then there might be some issue for both HDL and LDSC.

![image](https://user-images.githubusercontent.com/75370141/102346272-8c589200-3fd9-11eb-8b53-0e97196f9c02.png)
![image](https://user-images.githubusercontent.com/75370141/102346457-d04b9700-3fd9-11eb-81df-f9a7d35e532b.png)
I used my own file name, the data format conversion was complete, and the HDL operation didn't work at all
I am eager to get your help

**Comment by fry3682665** [comment]
> > It is not a test file, but my own GWAS Summary file, because in my previous use it seems that the HDL operation can only be performed if I change my file name to the same file name as the test file and remove the test file.
> 
> HDL should be smarter :) You should be able to specify your own file name by setting `gwas1.df=` and `gwas1.df=`.
> 
> > ![image](https://user-images.githubusercontent.com/75370141/102336576-4fd26980-3fcc-11eb-914d-8d8ae43bce2a.png)
> > This is my data. Is there a problem with the data?Another request is that I am also having trouble with this data when doing LDSC analysis. The problem has been commented on the GIthub of LDSC and I really hope to get your advice
> 
> The only thing I find a bit abnormal according to the screenshot is that most of SNPs are without rsid. How many SNPs you have in the GWAS files? Could you try to run with UKB_imputed_SVD_eigen99_extraction reference panel? This is the most standard panel we recommend our users to use. This panel is a subset of LDSC 1000 Genomes panel. If too many SNPs in this panel miss in your GWAS, then there might be some issue for both HDL and LDSC.

![image](https://user-images.githubusercontent.com/75370141/102346272-8c589200-3fd9-11eb-8b53-0e97196f9c02.png)
![image](https://user-images.githubusercontent.com/75370141/102346457-d04b9700-3fd9-11eb-81df-f9a7d35e532b.png)
I used my own file name, the data format conversion was complete, and the HDL operation didn't work at all
I am eager to get your help

**Comment by zhenin** [comment]
The names of arguments for HDL should be: 'gwas1.df' and 'gwas2.df', instead of 'asd.df' and 'ra.df'. You can change them and try it again.
