### ISSUE TITLE
error in both R and command line

### ISSUE THREAD

**Issue by jielab** [zhenin/HDL#27]
Hi!

![image](https://user-images.githubusercontent.com/26947455/138192040-3c3900b0-21f9-47dd-9c4a-ef784409c93d.png)

Please see the above screenshot, I got an error from R .

![image](https://user-images.githubusercontent.com/26947455/138192130-2bdd87bf-acb0-4cf4-964f-86c9693fc4f0.png)

Please see the above screenshot, I also got an error from command line version.

Can you please let me know what I did wrong here?

Thanks!

Jie

**Comment by now2014** [comment]
Hi,

Thanks for your feedback!
Could you please show me the content of the LD reference folder? (`ls D:/data/ldsc/UKB_imputed_SVD_eigen99_extraction`)

**Comment by jielab** [comment]
Thank you very much! Now it works, after I removed the two files ending with "(1).Rdata" !
I assume these two files were generated when my downloading was interrupted and then got reconnected again. I assume that your HDL R script first calculates the number of files in the reference directory and then output an error if the file count is incorrect. Don't know if it is a good idea to modify your script a little bit so that it allows extra dummy files.

Please see the screenshot below. Even though now HDL runs, it could NOT calculate the genetic correlation between my two GWAS, because the first GWAS has a heritability of 0! The first GWAS is 
a COVID-19 GWAS published last year on NEJM, so it is a very important GWAS, and that is why I try to dig into this.  

BTW, I am a faculty at PKU https://sph.pku.edu.cn/info/1409/4174.htm
Don't know if Dr. Shen could still be reached at xia.shen@ed.ac.uk.

![image](https://user-images.githubusercontent.com/26947455/138372519-d9f51225-2732-439b-9252-abb52b9a780a.png)

![image](https://user-images.githubusercontent.com/26947455/138372550-93d3ee58-639e-4d64-91c9-7d3181b430ec.png)
