### ISSUE TITLE
Build reference panel for EAS-ancestry population 

### ISSUE THREAD

**Issue by cwnag-c** [zhenin/HDL#29]
Hello,
  I would like to calculate the overall genetic correlation using EAS population data. However, I currently do not have a reference panel specifically designed for the EAS population. My question is, can I utilize the East Asian reference data provided by the CTG lab (https://ctg.cncr.nl/software/magma) to construct a suitable reference panel? I sincerely appreciate your assistance in resolving this matter!

Thank you,
ChaoWang

**Comment by now2014** [comment]
The sample size of EAS is relatively small, which is not ideal for constructing a reference panel. You can try and conduct simulations to test the EAS reference panel. See also #15.
It would be even better to use your GWAS sample to construct a reference panel.
