### ISSUE TITLE
GC >> 1

### ISSUE THREAD

**Issue by anbai106** [zhenin/HDL#31]
Hi, 

It seems that this software is no longer maintained, but I will try my luck here...

Overall, I found consistent results of HDL compared to LDSC, but I often saw inf/-inf/NAN estimates for GC and >>1. Was HDL bounded for the GC estimates??

Thanks

**Comment by now2014** [comment]
Hi,

Thanks for your report!

The intercept bound in genetic variance estimation is (-10, 10), and (0, 10) in heritability estimation.

I've added a `verbose` param to the `HDL.rg` and `HDL.rg.parallel` functions.
Can you set `verbose=TRUE` and re-run `HDL.rg` (or `HDL.rg.parallel`), to see what happened in the optimization process for a trait pair with inf/-inf/NAN intercept?

**Comment by anbai106** [comment]
Here is the output with verbose=TRUE:

```

INFO: Conflicting module gcc/9.4.0 detected and automatically unloaded.

WARNING: ignoring environment value of R_HOME
Function arguments:
gwas1.df=trait1.data.wrangling.hdl.rds
gwas2.df=trait2.data.wrangling.hdl.rds
LD.path=UKBB_HapMap3_LD_reference
output.file=trait1_vs_trait2.Rout
verbose=TRUE 

Loading GWAS1 ... 
Loading GWAS2 ... 

HDL: High-definition likelihood inference of genetic correlations and heritabilities (HDL)
Version 1.4.0 (2021-04-15) installed
Author: Zheng Ning, Xia Shen
Maintainer: Zheng Ning <zheng.ning@ki.se>

Tutorial: https://github.com/zhenin/HDL

Use citation("HDL") to know how to cite this work.

Analysis starts on Sun Dec 31 12:49:39 2023 
0 SNPs were removed in GWAS 1 due to missing N or missing test statistic.  
0 SNPs were removed in GWAS 2 due to missing N or missing test statistic.  
1017987 out of 1029876 (98.85%) SNPs in reference panel are available in GWAS 1.  
986178 out of 1029876 (95.76%) SNPs in reference panel are available in GWAS 2.  
Warning: More than 1% SNPs in reference panel are missed in GWAS 1. This may generate bias in estimation. Please make sure that you are using correct reference panel.  
Warning: More than 1% SNPs in reference panel are missed in GWAS 2. This may generate bias in estimation. Please make sure that you are using correct reference panel.  
Estimation is ongoing ... 100%

Integrating piecewise results 

Point estimates: 
Heritability of phenotype 1:  0.00e+00 
Heritability of phenotype 2:  0.1037 
Genetic Covariance:  -0.0015 
Genetic Correlation:  -Inf 
Warning: Heritability of one trait was estimated to be 0, which may due to:
          1) The true heritability is very small;
          2) The sample size is too small;
          3) Many SNPs in the chosen reference panel misses in the GWAS;
          4) There is a severe mismatch between the GWAS population and the population for computing reference panel
Continuing computing standard error with jackknife 
Progress... 100%

Heritability of phenotype 1:  0.00e+00 (0.0029) 
Heritability of phenotype 2:  0.1037 (0.0087) 
Genetic Covariance:  -0.0015 (0.0031) 
Genetic Correlation:  -Inf (0.5946) 
P:  0.00e+00 
Warning: Heritability of one trait was estimated to be 0, which may due to:
          1) The true heritability is very small;
          2) The sample size is too small;
          3) Many SNPs in the chosen reference panel misses in the GWAS.
Analysis finished at Sun Dec 31 12:55:39 2023 
The results were saved to trait1_vs_trait2.Rout
Finish!
```

**Comment by anbai106** [comment]
My two GWAS are all EUR ancestry. I think most of the SNPs overlaps with the UKBB reference LD panel after merging. I don't know the reason why trait1's h2=0. 

Not sure if this is because of the choice of the reference panel. I tried to generate the LD panel using 1000 Genomes EUR population, but ended up with some errors. Do you provide a pre-computed version?

**Comment by now2014** [comment]
Sorry, I misunderstood your meaning of `GC`. Anyway, the infinite `rg` estimation is due to the zero heritability of trait 1:

```math
r_g = \frac{\text{genetic covariance}}{\sqrt{h_1^2 \times h_2^2}}
```

The overlapped SNP seems to be OK as 98.85% SNPs in reference panel are available in trait 1. You may need to check the other two reasons:
1) The true heritability is very small; (you may try with LDSC)
2) The sample size is too small;

We currently don't provide pre-computed LD reference panel based on 1000 Genomes data. You can report your errors when building LD reference panel.

Thanks
