### ISSUE TITLE
Failed to install this package

### ISSUE THREAD

**Issue by MonnaHu** [zhenin/HDL#32]
1. method 1
 remotes::install_github("https://github.com/zhenin/HDL",build = F, force = TRUE)
Using github PAT from envvar GITHUB_TOKEN
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  Not Found

  Did you spell the repo owner (`zhenin`) and repo name (`HDL`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.

2. method 2
> try_error <- try(install.packages("HDL",
+                                   repos = NULL,
+                                   type = "source"), silent = TRUE)
WARNING: Rtools is required to build R packages but is not currently installed. Please download and install the appropriate version of Rtools before proceeding:

https://cran.rstudio.com/bin/windows/Rtools/
将程序包安装入‘C:/Users/meng1/AppData/Local/R/win-library/4.3’
(因为‘lib’没有被指定)
Warning: invalid package 'HDL'
Error: ERROR: no packages specified
Warning in install.packages :
  安装程序包‘HDL’时退出狀態的值不是0

**Comment by now2014** [comment]
Please refer to the doc for [installation](https://github.com/zhenin/HDL/wiki/Installation-and-update).
