### ISSUE TITLE
annot open file '/UKB_array_SVD_eigen90_extraction//': it is a directory

### ISSUE THREAD

**Issue by Dragonfly1108** [zhenin/HDL#36]
Hi,
I am encountering the following error while calculating genetic correlation using HDL.
Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
In addition: Warning message:
In readChar(con, 5L, useBytes = TRUE) :
  cannot open file '/UKB_array_SVD_eigen90_extraction//': it is a directory
What should I do to fix this error?
![屏幕截图 2024-07-26 235432](https://github.com/user-attachments/assets/45d3be7c-d930-4fcd-9fff-c7236d60b9bf)

**Comment by now2014** [comment]
Please refer to [this answer](https://github.com/zhenin/HDL/issues/34#issuecomment-2121684861), and make sure that all the files in your `UKB_array_SVD_eigen90_extraction` directory are matched: no missing or redundant files.
