### ISSUE TITLE
Add support for comparison of genetic correlations with the block jackknife

### ISSUE THREAD

**Issue by JoniColeman** [zhenin/HDL#4]
Hi,

One of the benefits of LDSC is the option to output the jackknife delete values used to estimate rg, which can then be used to calculate robust differences between rg(A,B) and rg(C,D) (see e.g. https://groups.google.com/g/ldsc_users/c/uZyjiabAorc/m/fgX2SoEuBAAJ).

Would it be possible/meaningful to have some similar option in HDL?

Thanks,

Joni

**Comment by zhenin** [comment]
Hi Joni,

Yes, it could be a useful feature. I will add it in the next version of HDL.

Thanks for your interest on HDL!

Best regards,
Zheng

**Comment by zhenin** [comment]
Hello again,

A new optional argument `jackknife.df` has been added in HDL v1.3.8. You can get the jackknife estimates by setting `jackknife.df=TRUE` in R or the command-line version. You can find more details [here](https://github.com/zhenin/HDL/wiki/Syntax-and-results-of-HDL#Estimating-genetic-correlation-using-HDL).

Thanks for your advice! I will close this issue. Please feel free to come back to me if there is any comment on `HDL`.

Best,
Zheng
