### ISSUE TITLE
Algorithm failed to converge after trying different initial values

### ISSUE THREAD

**Issue by Kai6662** [zhenin/HDL#6]
Hi,
When I tried to run HDL with your test data, I met error like this " HDL: High-definition likelihood inference of genetic correlations and heritabilities (HDL)
Version 1.3.8 (2020-07-12) installed
Author: Zheng Ning, Xia Shen
Maintainer: Zheng Ning <zheng.ning@ki.se>
Tutorial: https://github.com/zhenin/HDL
Use citation("HDL") to know how to cite this work.

Analysis starts on Mon Jul 20 11:29:25 2020
122913 out of 1029876 (11.93%) SNPs in reference panel are available in GWAS 1.
122913 out of 1029876 (11.93%) SNPs in reference panel are available in GWAS 2.
Warning: More than 1% SNPs in reference panel are missed in GWAS 1. This may generate bias in estimation. Please make sure that you are using correct reference panel.
Warning: More than 1% SNPs in reference panel are missed in GWAS 2. This may generate bias in estimation. Please make sure that you are using correct reference panel.

Integrating piecewise results
Algorithm failed to converge after trying different initial values." 
Here is a algorithm error. I  didn't change any raw example data.  Could you help me? I am looking forward to your reply. Thank!

Best regards,
Kai Cui

**Comment by zhenin** [comment]
Hi Kai,

Thanks for your interest in HDL! I think the problem is because you are using the imputed panel for LD (including ~ 1M SNPs) while using the example GWAS data for the array panel (such as gwas1.array.example.rds). Therefore there is a big mismatch.

In this case, you can try on the example GWAS data for the imputed panel following this [instruction](https://github.com/zhenin/HDL/wiki/Example-of-HDL-with-an-imputed-reference-panel). The example files `gwas1.imputed.example` and `gwas2.imputed.example` are the correct example data for the imputed panel.

Best regards,
Zheng

**Comment by Kai6662** [comment]
Thanks. It looks fine now.

**Comment by anbai106** [comment]
This error happens also even when using the UKBB imputed GWASs data: 

```
Function arguments:
gwas1.df=~/trait1.data.wrangling.hdl.rds
gwas2.df=~/trait2.data.wrangling.hdl.rds
LD.path=~/UKBB_HapMap3_LD_reference
output.file=~/trait1_vs_trait2.Rout

Loading GWAS1 ... 
Loading GWAS2 ... 

HDL: High-definition likelihood inference of genetic correlations and heritabilities (HDL)
Version 1.4.0 (2021-04-15) installed
Author: Zheng Ning, Xia Shen
Maintainer: Zheng Ning <zheng.ning@ki.se>

Tutorial: https://github.com/zhenin/HDL

Use citation("HDL") to know how to cite this work.

Analysis starts on Mon Oct  9 18:28:20 2023 
0 SNPs were removed in GWAS 1 due to missing N or missing test statistic.  
0 SNPs were removed in GWAS 2 due to missing N or missing test statistic.  
986178 out of 1029876 (95.76%) SNPs in reference panel are available in GWAS 1.  
986178 out of 1029876 (95.76%) SNPs in reference panel are available in GWAS 2.  
Warning: More than 1% SNPs in reference panel are missed in GWAS 1. This may generate bias in estimation. Please make sure that you are using correct reference panel.  
Warning: More than 1% SNPs in reference panel are missed in GWAS 2. This may generate bias in estimation. Please make sure that you are using correct reference panel.  
Estimation is ongoing ... 100%

Integrating piecewise results 
Error in HDL.rg(gwas1.df, gwas2.df, LD.path, Nref = Nref, N0 = N0, output.file = output.file,  : 
  Algorithm failed to converge after trying different initial values. 
Execution halted
```
